// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/jessicatarra/greenlight/ms/auth/domain"
	mock "github.com/stretchr/testify/mock"
)

// Appl is an autogenerated mock type for the Appl type
type Appl struct {
	mock.Mock
}

// ActivateUseCase provides a mock function with given fields: tokenPlainText
func (_m *Appl) ActivateUseCase(tokenPlainText string) (*domain.User, error) {
	ret := _m.Called(tokenPlainText)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUseCase")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return rf(tokenPlainText)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = rf(tokenPlainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenPlainText)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUseCase provides a mock function with given fields: input
func (_m *Appl) CreateUseCase(input domain.CreateUserRequest) (*domain.User, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUseCase")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateUserRequest) (*domain.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateUserRequest) *domain.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.CreateUserRequest) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmailUseCase provides a mock function with given fields: input
func (_m *Appl) GetByEmailUseCase(input domain.CreateUserRequest) (*domain.User, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmailUseCase")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateUserRequest) (*domain.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateUserRequest) *domain.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.CreateUserRequest) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAppl creates a new instance of Appl. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppl(t interface {
	mock.TestingT
	Cleanup(func())
}) *Appl {
	mock := &Appl{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
