// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	domain "github.com/jessicatarra/greenlight/ms/auth/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TokenInterface is an autogenerated mock type for the TokenInterface type
type TokenInterface struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: userID, ttl, scope
func (_m *TokenInterface) GenerateToken(userID int64, ttl time.Duration, scope string) (*domain.Token, error) {
	ret := _m.Called(userID, ttl, scope)

	var r0 *domain.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, time.Duration, string) (*domain.Token, error)); ok {
		return rf(userID, ttl, scope)
	}
	if rf, ok := ret.Get(0).(func(int64, time.Duration, string) *domain.Token); ok {
		r0 = rf(userID, ttl, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, time.Duration, string) error); ok {
		r1 = rf(userID, ttl, scope)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenInterface creates a new instance of TokenInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenInterface {
	mock := &TokenInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
