// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: auth.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthGRPCServiceClient is the client API for AuthGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGRPCServiceClient interface {
	ValidateAuthToken(ctx context.Context, in *ValidateAuthTokenRequest, opts ...grpc.CallOption) (*User, error)
	UserPermission(ctx context.Context, in *UserPermissionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type authGRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGRPCServiceClient(cc grpc.ClientConnInterface) AuthGRPCServiceClient {
	return &authGRPCServiceClient{cc}
}

func (c *authGRPCServiceClient) ValidateAuthToken(ctx context.Context, in *ValidateAuthTokenRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.AuthGRPCService/ValidateAuthToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGRPCServiceClient) UserPermission(ctx context.Context, in *UserPermissionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.AuthGRPCService/UserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthGRPCServiceServer is the server API for AuthGRPCService service.
// All implementations must embed UnimplementedAuthGRPCServiceServer
// for forward compatibility
type AuthGRPCServiceServer interface {
	ValidateAuthToken(context.Context, *ValidateAuthTokenRequest) (*User, error)
	UserPermission(context.Context, *UserPermissionRequest) (*empty.Empty, error)
	mustEmbedUnimplementedAuthGRPCServiceServer()
}

// UnimplementedAuthGRPCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthGRPCServiceServer struct {
}

func (UnimplementedAuthGRPCServiceServer) ValidateAuthToken(context.Context, *ValidateAuthTokenRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAuthToken not implemented")
}
func (UnimplementedAuthGRPCServiceServer) UserPermission(context.Context, *UserPermissionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserPermission not implemented")
}
func (UnimplementedAuthGRPCServiceServer) mustEmbedUnimplementedAuthGRPCServiceServer() {}

// UnsafeAuthGRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGRPCServiceServer will
// result in compilation errors.
type UnsafeAuthGRPCServiceServer interface {
	mustEmbedUnimplementedAuthGRPCServiceServer()
}

func RegisterAuthGRPCServiceServer(s grpc.ServiceRegistrar, srv AuthGRPCServiceServer) {
	s.RegisterService(&AuthGRPCService_ServiceDesc, srv)
}

func _AuthGRPCService_ValidateAuthToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAuthTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGRPCServiceServer).ValidateAuthToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthGRPCService/ValidateAuthToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGRPCServiceServer).ValidateAuthToken(ctx, req.(*ValidateAuthTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGRPCService_UserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGRPCServiceServer).UserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthGRPCService/UserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGRPCServiceServer).UserPermission(ctx, req.(*UserPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthGRPCService_ServiceDesc is the grpc.ServiceDesc for AuthGRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthGRPCService",
	HandlerType: (*AuthGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAuthToken",
			Handler:    _AuthGRPCService_ValidateAuthToken_Handler,
		},
		{
			MethodName: "UserPermission",
			Handler:    _AuthGRPCService_UserPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
