// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	app "github.com/jessicatarra/greenlight/ms/auth/app"
	entity "github.com/jessicatarra/greenlight/ms/auth/entity"

	mock "github.com/stretchr/testify/mock"
)

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *App) Create(input app.CreateUserRequest) (*entity.User, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(app.CreateUserRequest) (*entity.User, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(app.CreateUserRequest) *entity.User); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(app.CreateUserRequest) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewApp creates a new instance of App. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *App {
	mock := &App{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
