// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handlers is an autogenerated mock type for the Handlers type
type Handlers struct {
	mock.Mock
}

// activateUser provides a mock function with given fields: res, req
func (_m *Handlers) activateUser(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// createAuthenticationToken provides a mock function with given fields: res, req
func (_m *Handlers) createAuthenticationToken(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// createUser provides a mock function with given fields: res, req
func (_m *Handlers) createUser(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// NewHandlers creates a new instance of Handlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handlers {
	mock := &Handlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
