// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Middlewares is an autogenerated mock type for the Middlewares type
type Middlewares struct {
	mock.Mock
}

// authenticate provides a mock function with given fields: next
func (_m *Middlewares) authenticate(next http.Handler) http.Handler {
	ret := _m.Called(next)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// requireActivatedUser provides a mock function with given fields: next
func (_m *Middlewares) requireActivatedUser(next http.HandlerFunc) http.HandlerFunc {
	ret := _m.Called(next)

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(http.HandlerFunc) http.HandlerFunc); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// requirePermission provides a mock function with given fields: code, next
func (_m *Middlewares) requirePermission(code string, next http.HandlerFunc) http.HandlerFunc {
	ret := _m.Called(code, next)

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(string, http.HandlerFunc) http.HandlerFunc); ok {
		r0 = rf(code, next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// NewMiddlewares creates a new instance of Middlewares. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddlewares(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middlewares {
	mock := &Middlewares{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
