// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Resource is an autogenerated mock type for the Resource type
type Resource struct {
	mock.Mock
}

// activateUser provides a mock function with given fields: res, req
func (_m *Resource) activateUser(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// createAuthenticationToken provides a mock function with given fields: res, req
func (_m *Resource) createAuthenticationToken(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// createUser provides a mock function with given fields: res, req
func (_m *Resource) createUser(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// NewResource creates a new instance of Resource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResource(t interface {
	mock.TestingT
	Cleanup(func())
}) *Resource {
	mock := &Resource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
